version: "3.8"

services:
    php:
        build: 
            context: ../
            dockerfile: docker/Dockerfile
        container_name: statsfm-php
        restart: unless-stopped
        ports:
            - "2812:80"
        volumes:
            - cache:/var/www/html/cache

volumes:
    cache:
