name: Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: "[BACKEND] 🚀 Deploy"
      uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
      with:
        source: "./*, !./.git/**, !./.github/**"
        target: "./sites/${{ secrets.BACKEND_SERVER_FOLDER }}"
        host: ${{ secrets.BACKEND_SERVER_IP }}
        username: ${{ secrets.BACKEND_SERVER_USER }}
        password: ${{ secrets.BACKEND_SERVER_PASSWORD }}

    - name: "[BACKEND] 📦 Install dependencies"
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKEND_SERVER_IP }}
        username: ${{ secrets.BACKEND_SERVER_USER }}
        password: ${{ secrets.BACKEND_SERVER_PASSWORD }}
        script: |
          cd ./sites/${{ secrets.BACKEND_SERVER_FOLDER }}
          composer install